version: "3"

volumes:
  data_db:

networks:
  net:

services:
  mariadb:
    image: wodby/mariadb:10.3-3.6.8
    networks:
      - net
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"
    volumes:
      - data_db:/var/lib/mysql # Use bind mount

  php:
    image: rafa87garcia/azure-drupalphp
    networks:
      - net
    depends_on:
      - mariadb
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
#      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S opensmtpd:25
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      COLUMNS: 80 # Set 80 columns for docker exec -it.


  nginx:
    image: rafa87garcia/azure-nginx
    depends_on:
      - php
      - mariadb
    networks:
      - net
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: drupal8
    ports:
      - "80:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - net

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
